# NUMPY ARRAY AND OPERATIONS

In [4]:
import numpy as np


#### 1d arrays

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


#### 2d array


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


#### 3d array


In [7]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### special array creation

In [9]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### ones matrix

In [10]:
arr=np.ones([3,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### identity matrix

In [11]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### range

In [14]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


#### INDEXING IN NUMPY

#### 1d arrays

In [15]:
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


#### 2d arrays

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3d arrays

In [17]:
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### 3d arrays

In [18]:
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[0,0,0])

1


#### slicing in numpy

#### 1d arrays

In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr[0:5])
print(arr[5:10])
print(arr[0:10:2])
print(arr[:4])


[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[1 3 5 7 9]
[1 2 3 4]


#### 2d arrays

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


#### 3d arrays

In [21]:
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[0:2, 0:2, 0:2])
print(arr[0,:,:])
print(arr[:,0,:])
print(arr[:,:,0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


#### methemetical operatons

In [22]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
