# NUMPY OPERATION IN PYTHON WITH JUPYTER NOTEBOOK

In [1]:
import numpy as np

#### combinig arrays

### horizontal stacks

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
r=np.hstack((a,b))
print(r)

[ 1  2  3  4  5  6  7  8  9 10]


#### vertical stacks

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
r=np.vstack((a,b))
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## spliting array

In [5]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
r=np.split(arr,2)
print(r)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


## search function

#### find index

In [6]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
index=np.where(arr>50)
print(index)

(array([5, 6, 7, 8, 9]),)


## search sorted function

In [7]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
position=np.searchsorted(arr,50)
print(position)

4


## sort functions

In [8]:
arr = np.array([1,2,3,2,7,4,9,0,1])
print(np.sort(arr))

[0 1 1 2 2 3 4 7 9]


## aggregating & statistical functions

In [9]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print("sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))
print("median:",np.median(arr))

sum: 550
mean: 55.0
max: 100
min: 10
median: 55.0


## filter array

In [10]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
r=arr[arr>50]
print(r)

[ 60  70  80  90 100]


## multiple condition

In [11]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
r=arr[(arr>20)&(arr<80)]
print(r)

[30 40 50 60 70]


## masking arrays

In [12]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
mask=arr>50
r=arr[mask]
print(r)
filtered=arr[mask]
print(filtered)

[ 60  70  80  90 100]
[ 60  70  80  90 100]


## reshaping arrays

#### 1d to 3d

In [13]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
r=arr.reshape(2,5)
print(r)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


#### 1d to 2d

In [18]:
arr=np.array([10,20,30,40,50,60,70,80])
r=arr.reshape(2,2,2)
print(r)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


#### 3d to 1d

In [19]:
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
r=arr.reshape(8)
print(r)

[1 2 3 4 5 6 7 8]


### array broad casting

In [21]:
a=np.array([[1], [4], [5]])
b=np.array([2,3,4])
r=a+b
print(r)

[[3 4 5]
 [6 7 8]
 [7 8 9]]
